### ISSUE TITLE
Not working on version 2

### ISSUE THREAD

**Issue by zakiaziz** [jaanauati/hyper-search#18]
![screen shot 2017-10-19 at 4 32 27 pm](https://user-images.githubusercontent.com/940281/31792759-1e15dc52-b4eb-11e7-8dca-55bba14dd462.png)

I have not tried it on version 1, but on version 2 nothing happens when I hit `cmd` + `f` or going to `edit -> find -> toggle find bar`

**Comment by jaanauati** [comment]
Yeah seems to be the same folks already reported in #12, will close this one out as soon as I confirm it

**Comment by jaanauati** [comment]
just merged and published to npm v0.0.7 with a fix for this.
https://github.com/jaanauati/hyper-search/pull/20
@zakiaziz can u please give it a shot and let me know if this works for u?

thanks

**Comment by zakiaziz** [comment]
Just tried to update plugins and am seeing this 
![screen shot 2017-11-24 at 6 35 15 pm](https://user-images.githubusercontent.com/940281/33225474-46a43b42-d146-11e7-90cf-78ae67aac502.png)

I'll try again sometime this weekend and see if detects the npm update

**Comment by zakiaziz** [comment]
actually removed the plugin all together and reinstalled it. seems to work now
![screen shot 2017-11-24 at 6 37 40 pm](https://user-images.githubusercontent.com/940281/33225492-a1e6f440-d146-11e7-9f67-d9749d03553a.png)

**Comment by jaanauati** [comment]
thanks @zakiaziz for your quick response!, closing out this ticket.

**Comment by viveklanjekar** [comment]
@zakiaziz reinstaling works

**Comment by zakiaziz** [comment]
@viveklanjekar this is over a 2 year old issue that was clearly solved.
