### ISSUE TITLE
Support return key for next result

### ISSUE THREAD

**Issue by willrstern** [jaanauati/hyper-search#22]
The behavior for most search apps (Chrome, iTerm, etc) is:

While focused on the search input:
- return highlights/goes-to the next result
- shift+return highlights/goes-to the previous result

Allowing the user to hit return, return, return, to cycle through all available results easily.

This would be a nice feature, or at least nice to be able to configure

**Comment by jaanauati** [comment]
pull request merged and stuff published, closing out this ticket.
thanks.
