### ISSUE TITLE
Incompatible with newer node versions.

### ISSUE THREAD

**Issue by dallasthiele** [jaanauati/hyper-search#31]
I receive an error when loading this add-on as it's incompatible with my version of node (9.5.0). The error says it's looking for ">=0.4.x < 0.7.0"

**Comment by jaanauati** [comment]
hi, i'm having issues to replicate this... went to hyper.is, downloaded the latest release (2.0.0), deleted my local copy of hyper-search and reinstalled it with `hyper i hyper-search`, then reloaded the terminal and the plugin loaded just fine.
could u please list the steps you are following? 
thanks

**Comment by dallasthiele** [comment]
My bad, turns out there was a plugin called search in the plugins folder next to hyper-search. Don't remember installing that one but it was the one throwing errors. This plugin is working great now!
