### ISSUE TITLE
Doesn't work on Ubuntu

### ISSUE THREAD

**Issue by roccomuso** [jaanauati/hyper-search#33]
It doesn't work with Ubuntu and Hyper 2.0.0

**Comment by canmihci** [comment]
confirmed

**Comment by jaanauati** [comment]
have u tried with opening it from the menu?  (Edit->find)

**Comment by jaanauati** [comment]
please try with 0.0.10  and let me know (see https://github.com/jaanauati/hyper-search/issues/12).

**Comment by friday** [comment]
Same thing on Arch. Edit -> find -> Toggle Find Bar (or ctrl + shift + f) doesn't do anything.

**Comment by bmihelac** [comment]
It works on Ubuntu 18.10, with Ctrl-Shift-F:

![screenshot from 2018-12-10 17-31-27](https://user-images.githubusercontent.com/13813/49746429-7b197400-fca1-11e8-9581-8b6e8eb70663.png)

Styles are little weird for the default theme.

**Comment by jaanauati** [comment]
closing this one out, the styling issues will be addressed w https://github.com/jaanauati/hyper-search/issues/39.
