### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by limonkufu** [jaanauati/hyper-search#38]
Tried the plugin but couldn't get it to work on Windows

**Comment by jaanauati** [comment]
Hi @Limonkufu, are the shortcuts not working or it is that the 'find' submenu doesn't populate either?, been testing on windows couple of months ago and I noticed that sometimes when installing / updating the plugin I had to restart the app (closing and opening it again) to get hyper-search working, could u please try that?

**Comment by limonkufu** [comment]
After uninstalling and installing hyper again, it worked. I don't know what went wrong. Thanks for the help anyways.

**Comment by mandaputtra** [comment]
Strange hyper-search doesn't show up on my terminal. No 'find' menu. I tried to reinstall and reload
