### ISSUE TITLE
Looks crap on Windows

### ISSUE THREAD

**Issue by johnknoop** [jaanauati/hyper-search#39]
![image](https://user-images.githubusercontent.com/3394270/45221823-f63e4900-b2b2-11e8-8f41-bc375ac039c9.png)

**Comment by erkattak** [comment]
Same on linux ![image](https://user-images.githubusercontent.com/324258/46289026-b9820c80-c555-11e8-8f62-4a8ecfe11a4a.png)

**Comment by divyanshu013** [comment]
The alignment is also off in Fedora 
![screenshot from 2018-11-09 14-57-04](https://user-images.githubusercontent.com/6682655/48254389-ef0cf600-e42f-11e8-809d-e6bf37242b20.png)

**Comment by AaronAsAChimp** [comment]
I was able to fix most of the visual issues by adding this to my '.hyper.js'. I don't think much that can be done about the emojis without a PR.

```js
module.exports = {
    css: `
      .hyper-search-wrapper {
        display: flex;
      }

      .hyper-search-wrapper button {
        position: static !important;
      }
    `
}
```
![image](https://user-images.githubusercontent.com/60481/54707152-d071e680-4b16-11e9-86ac-6b1b5e864b74.png)

**Comment by thomasfedb** [comment]
Currently looks like this on fedora:

![image](https://user-images.githubusercontent.com/193831/59678685-a3110380-91ff-11e9-924e-29b567c6b383.png)

**Comment by jaanauati** [comment]
unfortunately I don't have Windows or linux envs handy, will try to pull a vm and test this in the following weeks.

**Comment by jaanauati** [comment]
hyper-search v0.3.0 has been published to npm; this version has some styling improvements and fixes that seem to address the issues reported in this ticket (see https://github.com/jaanauati/hyper-search/pull/67... thank you @ng-hai !!!!).

See my screenshot, I tested in a windows virtual machine and it seems like the issues have been fixed:
<img width="1041" alt="Screen Shot 2019-07-09 at 18 42 57" src="https://user-images.githubusercontent.com/433609/60925298-a8e78b00-a279-11e9-934b-a52f0dbdd594.png">

@thomasfedb can u please let me know if this is also fixing the issues for linux?

thanks

**Comment by thomasfedb** [comment]
@jaanauati appears resolved on Linux (Fedora) also.

**Comment by jaanauati** [comment]
thank you @thomasfedb !
