### ISSUE TITLE
Not working in MacOS Mojave

### ISSUE THREAD

**Issue by migueloop** [jaanauati/hyper-search#41]
Hi!

I added this plugin to hyper but didn't allowed me to search (nothing happening with cmd + f) and also disabled me of doing cmd + d to open new frames.

How could I add more info about the bug?

Thanks in advance

**Comment by jonatananauati-natgeo** [comment]
Hi!, the plugin is working for me in Mojave, have u also tried restarting hyper? if u have already done that and it keeps not working it would be great to have the following info:
 - plugins: what other plugins you are using (perhaps it's easier if u share your config file).
 - hyper version.

Thanks.

**Comment by jaanauati** [comment]
closing out due to inactivity, @migueloop feel free to re-open if u still have issues.
