### ISSUE TITLE
Doesn't work after HyperJS update

### ISSUE THREAD

**Issue by MircoT** [jaanauati/hyper-search#42]
> HyperJS version: `2.1.3`
>
> Plugins:
>  *  hyper-pane `2.1.3`,
>  *  hyper-night-owl `1.1.0`,
>  *  hyper-search `0.0.10`
>
> OS: macOS Mojave `10.14.2`

**Error**: 
```javascript
Uncaught TypeError: term.getRowCount is not a function
    at HyperSearchTerm.legacySearch (.../.hyper_plugins/node_modules/hyper-search/src/containers.js:312)
```

It seems that **term** doesn't have anymore that function. If you substitute `getRowCount` with the attribute `rows` then you will have a problem with `getNode` function, that is not available too.

**Comment by m-grzybek-first10** [comment]
I'm getting the same error
```
HyperJS version: 2.1.0
Plugins: 
  hyper-material-theme (2.0.8),
  hyper-search (0.0.10)
OS: MacOS High Sierra 10.13.6
```

**Comment by jaanauati** [comment]
Sorry abt the delay, I just merged some changes to deal with some breaking changes made at hyperjs side. (https://github.com/jaanauati/hyper-search/pull/43),  will be pushing the new version to npm soon.

**Comment by jaanauati** [comment]
@m-grzybek-first10  @MircoT, v0.0.11 has been published to the npm registry, please give it a try and let me know. thanks!.

**Comment by m-grzybek-first10** [comment]
@jaanauati works like a charm :) thanks a lot !

**Comment by MircoT** [comment]
Also for me! Thanks @jaanauati !
