### ISSUE TITLE
contributors section

### ISSUE THREAD

**Issue by jaanauati** [jaanauati/hyper-search#50]
https://github.com/jaanauati/hyper-search/pull/47 added the collaborators section in the readme.

@willrstern @ManUtopiK @alex-cory @deiga @aldudalski 

you guys eventually contributed to this extension and i'd like to add your names (and links to your github profiles) to the Readme, please let me know if u agree/disagree.

thanks.

**Comment by ManUtopiK** [comment]
👍 Thanks!

**Comment by deiga** [comment]
👍  Much appreciated

**Comment by aldudalski** [comment]
Definitely. Thanks

**Comment by willrstern** [comment]
👍 (late from being on PTO) awesome!

**Comment by jaanauati** [comment]
@willrstern @ManUtopiK  @deiga @aldudalski you have been added to the readme and package.json files.

I'm closing this ticket out now, @alex-cory let me know if u'd like to be added or just submit a pull request.

thanks.
