### ISSUE TITLE
Hyper search removes custom styles defined in `~/.hyper.js`

### ISSUE THREAD

**Issue by navinpeiris** [jaanauati/hyper-search#56]
Custom CSS defined within a users `~/.hyper.js` using the `css` option is discarded when this plugin is loaded.

A quick look points to this line here, but haven't debugged it further: https://github.com/jaanauati/hyper-search/commit/496a128719f8b7a83ceb7c38631c5d2dc350b12d#diff-84b8ab4a26f4fc294f90328327aa66d3R28

**Comment by jaanauati** [comment]
I just made this pull request, haven't tested locally, but i believe this should fix the issue: https://github.com/jaanauati/hyper-search/pull/57, are u able to make this tweak locally (~/.hyper_plugins/node_modules/hyper-search/src/containerStyles.js and tell me if it works for u?). I will be testing and pushing a release later by the end of the day. thanks.

**Comment by jaanauati** [comment]
Fix pushed to npm: hyper-search@0.2.1.
