### ISSUE TITLE
Search bottom up

### ISSUE THREAD

**Issue by hector** [jaanauati/hyper-search#66]
Currently the search is done like you would expect in a file: first found element is the first from the begging of the file, and then next etc until the bottom.

When I search on the shell I normally prefer to find the occurrences from the bottom to the top.
Is this something configurable in the plugin?

**Comment by hector** [comment]
BTW, this is the behaviour of iTerm

**Comment by samuelyeungkc** [comment]
this is actually easy. swap ahdleSearchPrev and handleSearchNext would solve this problem

In containers.js
> if (event.key === ENTER && event.shiftKey) {
>           this.handleSearchPrev();
>         } else if (event.key === ENTER) {
>           this.handleSearchNext();

**Comment by jaanauati** [comment]
implemented in v0.4.0.
